# Generated by Django 4.1.7 on 2023-02-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeSantiago',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('href', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('stations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstacionBicicletas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('empty_slots', models.IntegerField()),
                ('free_bikes', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('bike_santiago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bikesantiago')),
            ],
        ),
    ]
